Check if any commits were added

diff --git a/.github/workflows/update-reuse-headers.yml b/.github/workflows/update-reuse-headers.yml
--- a/.github/workflows/update-reuse-headers.yml
+++ b/.github/workflows/update-reuse-headers.yml
@@ -49,7 +49,7 @@ jobs:
 
           echo "Fetching files for PR #${PR_NUMBER} in repo ${GH_REPO}"
 
-          PR_FILES_JSON=$(curl -s -f \
+          PR_FILES_JSON=$(curl -s -f -H "Authorization: token ${GH_TOKEN}" \
             "https://api.github.com/repos/${GH_REPO}/pulls/${PR_NUMBER}/files")
 
           if [ $? -ne 0 ]; then
@@ -79,6 +79,30 @@ jobs:
         run: |
           reuse lint-file $(echo "${{ env.PR_FILES_LIST }}" | tr '\n' ' ')
         working-directory: ${{ github.workspace }}
+
+      - name: Check for added commits
+        env:
+          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
+          GH_REPO: ${{ github.repository }}
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+        run: |
+          set -e # Exit script on first error
+
+          echo "Fetching commits for PR #${PR_NUMBER} in repo ${GH_REPO}"
+
+          PR_COMMIT_JSON=$(curl -s -f -H "Authorization: token ${GH_TOKEN}" \
+            "https://api.github.com/repos/${GH_REPO}/pulls/${PR_NUMBER}/commits?per_page=1")
+
+          if [ $? -ne 0 ]; then
+            echo "Error fetching commits from GitHub API."
+            exit 1
+          fi
+
+          PR_COMMIT_SHA=$(echo "$PR_COMMIT_JSON" | jq -r '.[0] | "\(.sha)"')
+
+          echo "Found commit sha $PR_COMMIT_SHA"
+
+          [[ $(git rev-parse HEAD) == $PR_COMMIT_SHA ]]
 
       - name: Commit changes
         uses: stefanzweifel/git-auto-commit-action@v5
